### PR TITLE
Home Page styling and compatibility  bugs

### PR DESCRIPTION
**Pull request by Karyum**
ref #73 #71 #78 
Nav bar would be fixed in a different PR
also for some reason everything is dark in the screenshots its my screen not the page itslef
q

screenshot-from-2017-07-18-12_47_45

### CODE REVIEW

**Comment by Suuuuha** [comment]
@Karyum  I think it would be better if we make the submission form look more similar to the 'contact us' that was suppost to be on the same page !
as shown in here:

screenshot from 2017-07-17 12 42 28

**Comment by lucyrose93** [comment]
Hey, I know this is a work in progress, but my comments are: 
- text-align left with padding needed
- the cartoon pictures look a little childish -- is there a reason why we aren't using photos? 
@Suuuuha @Karyum

**Comment by Suuuuha** [comment]
@lucyrose93 You are right, there is no specific reason, could we just choose any 4-5 photos to replace the ones used now or you prefer sending us the ones you used in the wireframe?

**Comment by lucyrose93** [comment]
@Suuuuha I have added the source images to the inVision [assets folder](https://support.invisionapp.com/hc/en-us/articles/115000633466-Assets), which you should be able to access as collaborators.
Let me know if you can't access it, and I can WhatsApp them to you.

**Comment by Suuuuha** [comment]
Just saw them .. cheers

**Comment by lucyrose93** [comment]
Looking good @Suuuuha @Karyum 👍 
Remember to align the text left; at the moment it is centered. 
There will be more options in the nav bar: Events and News
Copy needs to be added underneath the search bar, in line with the latest wireframes
The form input fields look a little dark -- maybe change the opacity? 
Think about padding/margins around the text. "Arab Innovators" is a little high up, for example. 
Bonne chance 😄

**Comment by Karyum** [comment]
@lucyrose93 the nav bar is going to be in a different PR ( #80 ) and the popular search and description is also in a ( #81 ) and the rest is on its way :smile:

**Comment by Karyum** [comment]
@lucyrose93 also theres a problem with my screenshots they are too dark for some reason they look different than my actual screen

**Comment by lucyrose93** [comment]
@Karyum That's good to know about the darkness.
Overall, it's looking great :)
I think it's a good idea to follow the styles for the 'contact us' section, as @Suuuuha suggests.

**Comment by Karyum** [comment]
screenshot-from-2017-07-18-12_47_45
@lucyrose93 its small for some reason (suha's fault :stuck_out_tongue_winking_eye: )but its the right color

**Comment by Suuuuha** [comment]
:shipit: mate

**Pull request merged**
