### PR TITLE
Style startup submission page

### PR DESCRIPTION
**Pull request by Karyum**
rel #38 
untitled

### CODE REVIEW

**Comment by Suuuuha** [comment]
@Karyum  looks good .. but maybe change the order (swap the company's name and the full name, and company's website with the funding stage) ?

**Comment by Karyum** [comment]
@Suuuuha  so the reason why it is ordered like this is because the whole idea of the website is about startups, thats why the startup name is first, and for the funding stage dropdown it's better ux if both drops down were one after the other so that the user wouldn't switch between mouse and keyboard much

**Comment by esraajb** [comment]
screen shot 2017-07-11 at 6 40 27 pm

**Comment by esraajb** [comment]
looks good, but please follow the order in the picture I uploaded. If you think that it should be in a different order, raise an issue and assign @lucyrose93 to discuss it.

and you missed the +add co-founder option

**Comment by Karyum** [comment]
Hey @lucyrose93 wanted to ask your opinion about the order of the submission form ?

**Comment by Suuuuha** [comment]
@Karyum in my older pull requests i've added classes for colors to use , I think its better to use them (e.g bg-granite-gray instead of gray) just to keep consistency.
And maybe move the options on the right a bit for the top and/or if we're keeping the sector option maybe move one of the options on the left to the right ?

**Comment by esraajb** [comment]
@Karyum as we are short in time, I think just follow Lucy`s order & styling.
 open an issue to discuss the changes you want for later improvements.

**Comment by Karyum** [comment]
@esraajb @Suuuuha @lucyrose93 I will reorder it then to look like the wireframe but what about the sector ?? should i keep it ? if yes where should i put it

**Comment by esraajb** [comment]
@Karyum under the company's name

**Comment by Suuuuha** [comment]
@Karyum conflict !

**Comment by Karyum** [comment]
untitled

@Suuuuha @esraajb resolved

**Comment by esraajb** [comment]
@Karyum also, the 'Co-Founder Name' should be optional.
and there is a margin top from the button to the funding stage field.
and and we should be consistent. the title says "STARTUP application" and we ask for "COMPANY`S name"
Let's work with 'startup'.
ok last and, 
the '100 words' in the description, should me 'up to 100 words'.

**Comment by Karyum** [comment]
@esraajb 
untitled

**Comment by lucyrose93** [comment]
@Karyum @esraajb @Suuuuha 
- I agree with your changes to the content 👍 
- Let's change "Up _tp_ 100 words" to "Up _to_ 100 words" 
- Also, is there any way we could move sector to be above funding stage on the right hand side? This way both sides will be balanced ⚖️

**Pull request merged**
