### PR TITLE
Search input Features

### PR DESCRIPTION
**Pull request by Karyum**
any
### Don't merge yet
rel #81 

@esraajb i wanted to ask if the links (for the popular searches ) should have a special functionality to render them or is it through the admin of the website ?

### CODE REVIEW

**Comment by esraajb** [comment]
@Karyum should have a special functionality. but in the meantime leave it to the admin.

**Comment by Karyum** [comment]
@esraajb then in the meantime we can review and merge this PR and when we make the admin route functionality i'll add the popular searches functionality

**Comment by esraajb** [comment]
@Suuuuha  review please

**Comment by esraajb** [comment]
@Suuuuha as we are short in time, I'm going to review this one

**Pull request merged**
