### PR TITLE
Handle error if startup already exists

### PR DESCRIPTION
**Pull request by Karyum**
rel #143

### CODE REVIEW

**Comment by Suuuuha** [comment]
@Karyum The 'not_found' page have the message 'sorry we couldn't find what you are looking for', if a user is trying to add a startup which already exists he should get a different alert/errorMessage

**Comment by Karyum** [comment]
@Suuuuha then that would be a separate issue that would labeled as bug, all im doing here is fixing the error handling in the page and increasing our coverage :maple_leaf:

**Comment by Karyum** [comment]
@Suuuuha can you please review this or do you stil want something to be changed?

**Comment by Suuuuha** [comment]
@Karyum I'm approving and opening new issue to change the error message

**Comment by Karyum** [comment]
@esraajb

**Pull request merged**
