### PR TITLE
Move search to nav-bar

### PR DESCRIPTION
**Pull request by Karyum**
rel #137 
screenshot from 2017-08-08 19-32-20

### CODE REVIEW

**Comment by Suuuuha** [comment]
@Karyum :+1:

**Comment by esraajb** [comment]
@Karyum add button to the search

**Comment by Karyum** [comment]
screenshot from 2017-08-09 12-00-18
@esraajb

**Comment by Karyum** [comment]
@Suuuuha can you review this now ?
thanks

**Pull request merged**
