### PR TITLE
All events page title

### PR DESCRIPTION
**Pull request by Karyum**
rel #152

@esraajb @Suuuuha Is this literally it (the change that needs to be done)?

### CODE REVIEW

**Comment by Suuuuha** [comment]
@Karyum exactly

**Comment by esraajb** [comment]
I think let's capitalize all the title, let's start from here. just add 'ttu' class.

**Comment by Karyum** [comment]
@esraajb are you sure it's ttu ? cause ttu is uppercase while ttc is capitalize

**Comment by esraajb** [comment]
yea meant uppercase

**Comment by Karyum** [comment]
how does this look ? @esraajb 
screenshot from 2017-08-16 00-57-01

**Comment by esraajb** [comment]
im not sure that I like that both the title and the events have the same width

**Comment by Karyum** [comment]
i got rid of ttu and this looks much better in my opinion

**Pull request merged**
