### PR TITLE
Style Results Page

### LINKED ISSUE #61: Style Results Page

### PR DESCRIPTION
**Pull request by Karyum**
untitled

close  #61 
i got rid of the div's so there is 1 MyCity startup now

### CODE REVIEW

**Comment by esraajb** [comment]
screen shot 2017-07-12 at 7 15 58 pm

**Comment by Karyum** [comment]
@esraajb what are the changes that you requested ?? just the checkboxes?

**Comment by Karyum** [comment]
@esraajb 
untitled

**Comment by Karyum** [comment]
# DO NOT MERGE

**Comment by Karyum** [comment]
untitled
- remove console errors on browser
- add submit button

**Comment by esraajb** [comment]
The checkboxes should be in a dropdown, as in the wireframe 
Ill merge for now, as we need this for tomorrow. 
Ill raise sn issue about it

**Pull request merged**
